export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_MY_TOPICS: 'FETCH_MY_TOPICS',
  FETCH_TIMELINE: 'FETCH_TIMELINE',
  FETCH_ALL: 'FETCH_ALL',
  FETCH_TOPIC: 'FETCH_TOPIC',
  FETCH_COMMENTS: 'FETCH_COMMENTS',
};
